Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -50,87 +50,87 @@ jobs:
   #       path: publish/*
 
   linux:
-  name: 'Linux'
-  runs-on: ubuntu-latest
-  container: s1lentq/linux86buildtools:latest
+    name: 'Linux'
+    runs-on: ubuntu-latest
+    container: s1lentq/linux86buildtools:latest
 
-  steps:
-  - name: Checkout
-    uses: actions/checkout@v3
-    with:
-      fetch-depth: 0
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v3
+      with:
+        fetch-depth: 0
 
-  # Build i386 version
-  - name: Build using Intel C++ Compiler 19.0 (i386)
-    run: |
-      rm -rf build && CC=icc CXX=icpc cmake -DCMAKE_BUILD_TYPE=COMPAT_GLIBC -B build/i386 && cmake --build build/i386 -j8
+    # Build i386 version
+    - name: Build using Intel C++ Compiler 19.0 (i386)
+      run: |
+        rm -rf build && CC=icc CXX=icpc cmake -DCMAKE_BUILD_TYPE=COMPAT_GLIBC -B build/i386 && cmake --build build/i386 -j8
 
-  - name: Prepare SDK for i386
-    run: |
-      mkdir -p publish/sdk
-      mkdir -p publish/addons/metamod
-      rsync -a \
-        --include=dllapi.h \
-        --include=engine_api.h \
-        --include=enginecallbacks.h \
-        --include=h_export.h \
-        --include=meta_api.h \
-        --include=mutil.h \
-        --include=plinfo.h \
-        --exclude='*' metamod/src/ publish/sdk
-      rsync metamod/extra/config.ini publish/addons/metamod
-      rsync -a metamod/extra/example/ publish/example_plugin
-      rsync -a publish/sdk/ publish/example_plugin/include/metamod
+    - name: Prepare SDK for i386
+      run: |
+        mkdir -p publish/sdk
+        mkdir -p publish/addons/metamod
+        rsync -a \
+          --include=dllapi.h \
+          --include=engine_api.h \
+          --include=enginecallbacks.h \
+          --include=h_export.h \
+          --include=meta_api.h \
+          --include=mutil.h \
+          --include=plinfo.h \
+          --exclude='*' metamod/src/ publish/sdk
+        rsync metamod/extra/config.ini publish/addons/metamod
+        rsync -a metamod/extra/example/ publish/example_plugin
+        rsync -a publish/sdk/ publish/example_plugin/include/metamod
 
-  - name: Move files for i386
-    run: |
-      mv build/i386/metamod/metamod_i386.so publish/addons/metamod/metamod_i386.so
-      mv metamod/version/appversion.h publish/appversion_i386.h
+    - name: Move files for i386
+      run: |
+        mv build/i386/metamod/metamod_i386.so publish/addons/metamod/metamod_i386.so
+        mv metamod/version/appversion.h publish/appversion_i386.h
 
-  - name: Run GLIBC/ABI version compat test (i386)
-    run: |
-      binaries=(
-        "publish/addons/metamod/metamod_i386.so"
-      )
-      bash ./metamod/version/glibc_test.sh ${binaries[@]}
-      if [[ $? -ne 0 ]]; then
-        exit 1 # Assertion failed
-      fi
-    shell: bash
+    - name: Run GLIBC/ABI version compat test (i386)
+      run: |
+        binaries=(
+          "publish/addons/metamod/metamod_i386.so"
+        )
+        bash ./metamod/version/glibc_test.sh ${binaries[@]}
+        if [[ $? -ne 0 ]]; then
+          exit 1 # Assertion failed
+        fi
+      shell: bash
 
-  # Build i686 version
-  - name: Build using Intel C++ Compiler 19.0 (i686)
-    run: |
-      rm -rf build && CC=icc CXX=icpc cmake -DCMAKE_BUILD_TYPE=COMPAT_GLIBC -B build/i686 && cmake --build build/i686 -j8
+    # Build i686 version
+    - name: Build using Intel C++ Compiler 19.0 (i686)
+      run: |
+        rm -rf build && CC=icc CXX=icpc cmake -DCMAKE_BUILD_TYPE=COMPAT_GLIBC -B build/i686 && cmake --build build/i686 -j8
 
-  - name: Move files for i686
-    run: |
-      mkdir -p publish/addons/metamod_i686
-      mv build/i686/metamod/metamod_i686.so publish/addons/metamod_i686/metamod_i686.so
-      mv metamod/version/appversion.h publish/appversion_i686.h
+    - name: Move files for i686
+      run: |
+        mkdir -p publish/addons/metamod_i686
+        mv build/i686/metamod/metamod_i686.so publish/addons/metamod_i686/metamod_i686.so
+        mv metamod/version/appversion.h publish/appversion_i686.h
 
-  - name: Run GLIBC/ABI version compat test (i686)
-    run: |
-      binaries=(
-        "publish/addons/metamod_i686/metamod_i686.so"
-      )
-      bash ./metamod/version/glibc_test.sh ${binaries[@]}
-      if [[ $? -ne 0 ]]; then
-        exit 1 # Assertion failed
-      fi
-    shell: bash
+    - name: Run GLIBC/ABI version compat test (i686)
+      run: |
+        binaries=(
+          "publish/addons/metamod_i686/metamod_i686.so"
+        )
+        bash ./metamod/version/glibc_test.sh ${binaries[@]}
+        if [[ $? -ne 0 ]]; then
+          exit 1 # Assertion failed
+        fi
+      shell: bash
 
-  - name: Deploy artifacts
-    uses: actions/upload-artifact@v3.1.1
-    id: upload-job
-    with:
-      name: linux32
-      path: publish/*
+    - name: Deploy artifacts
+      uses: actions/upload-artifact@v3.1.1
+      id: upload-job
+      with:
+        name: linux32
+        path: publish/*
 
-  - name: Cleanup temporary artifacts
-    if: success() && steps.upload-job.outcome == 'success'
-    run: |
-      rm -f appversion_i386.h appversion_i686.h
+    - name: Cleanup temporary artifacts
+      if: success() && steps.upload-job.outcome == 'success'
+      run: |
+        rm -f appversion_i386.h appversion_i686.h
 
 
   publish:
