test

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -55,69 +55,47 @@ jobs:
     container: s1lentq/linux86buildtools:latest
 
     steps:
-    - name: Git Clone
-      run: |
-        apt-get update
-        apt-get install -y git curl
-        cd ..
-        git clone https://github.com/antoniolago/metamod-r
-        cd metamod-r
-        git config --global --add safe.directory /__w/metamod-r/metamod-r
+    - name: Checkout
+      uses: actions/checkout@v3
+      with:
+        fetch-depth: 0
 
-    - name: Build using Intel C++ Compiler 19.0
-      run: |
-        rm -rf build && CC=icc CXX=icpc cmake -DCMAKE_BUILD_TYPE=COMPAT_GLIBC -B build && cmake --build build -j8
-
-    - name: Prepare SDK
-      run: |
-        mkdir -p publish/sdk
-        mkdir -p publish/addons/metamod
-        rsync -a \
-          --include=dllapi.h \
-          --include=engine_api.h \
-          --include=enginecallbacks.h \
-          --include=h_export.h \
-          --include=meta_api.h \
-          --include=mutil.h \
-          --include=plinfo.h \
-          --exclude='*' metamod/src/ publish/sdk
-        rsync metamod/extra/config.ini publish/addons/metamod
-        rsync -a metamod/extra/example/ publish/example_plugin
-        rsync -a publish/sdk/ publish/example_plugin/include/metamod
-
-    - name: Move files
-      run: |
-        mv build/metamod/metamod_i386.so publish/addons/metamod/metamod_i386.so
-        mv metamod/version/appversion.h publish/appversion.h
-
-    - name: Run GLIBC/ABI version compat test
-      run: |
-        binaries=(
-          "publish/addons/metamod/metamod_i386.so"
-        )
-        bash ./metamod/version/glibc_test.sh ${binaries[@]}
-        if [[ $? -ne 0 ]]; then
-          exit 1 # Assertion failed
-        fi
-      shell: bash
+    - name: Build inside Docker
+      uses: docker://s1lentq/linux86buildtools:latest
+      with:
+        entrypoint: ""
+        run: |
+          rm -rf build && CC=icc CXX=icpc cmake -DCMAKE_BUILD_TYPE=COMPAT_GLIBC -B build && cmake --build build -j8
+          mkdir -p publish/sdk
+          mkdir -p publish/addons/metamod
+          rsync -a \
+            --include=dllapi.h \
+            --include=engine_api.h \
+            --include=enginecallbacks.h \
+            --include=h_export.h \
+            --include=meta_api.h \
+            --include=mutil.h \
+            --include=plinfo.h \
+            --exclude='*' metamod/src/ publish/sdk
+          rsync metamod/extra/config.ini publish/addons/metamod
+          rsync -a metamod/extra/example/ publish/example_plugin
+          rsync -a publish/sdk/ publish/example_plugin/include/metamod
+          mv build/metamod/metamod_i386.so publish/addons/metamod/metamod_i386.so
+          mv metamod/version/appversion.h publish/appversion.h
+          binaries=(
+            "publish/addons/metamod/metamod_i386.so"
+          )
+          bash ./metamod/version/glibc_test.sh ${binaries[@]}
+          if [[ $? -ne 0 ]]; then
+            exit 1 # Assertion failed
+          fi
 
     - name: Deploy artifacts
-      run: |
-        # Define variables
-        ARTIFACT_NAME="linux32"
-        ARTIFACT_PATH="publish/*"
-        UPLOAD_URL="https://api.github.com/repos/${{ github.repository }}/actions/artifacts"
-    
-        # Create a tarball of the artifacts
-        tar -czvf ${ARTIFACT_NAME}.tar.gz -C publish .
-    
-        # Upload the tarball using curl
-        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
-             -H "Content-Type: application/gzip" \
-             --data-binary @${ARTIFACT_NAME}.tar.gz \
-             "${UPLOAD_URL}?name=${ARTIFACT_NAME}"
+      uses: actions/upload-artifact@v3.1.1
       id: upload-job
-
+      with:
+        name: linux32
+        path: publish/*
     - name: Cleanup temporary artifacts
       if: success() && steps.upload-job.outcome == 'success'
       run: |
